### ISSUE TITLE
PyPI version is still buggy

### ISSUE THREAD

**Issue by nicolashainaux** [nicolashainaux/sphinx-autodoc-annotation#5]
The bug that led to [this issue](https://github.com/hsoft/sphinx-autodoc-annotation/issues/2) and this [PR](https://github.com/hsoft/sphinx-autodoc-annotation/pull/3) is corrected in the github repo but is still in the PyPI package. So anytime it's installed from PyPI it triggers the bug.

Would this be possible to release a new minor version on PyPI (like 1.0.1) that would include this bug correction?

As long as the bug remains in the PyPI package, it's indeed not possible(*) to use sphinx-autodoc-annotation if one wants to build the doc on readthedocs, because it installs the buggy version from PyPI... isn't it a bit of a shame?

I find this package really useful to use along python3 annotations.

(*) maybe using a `dependency_links=['']` in `setup()` but this is not really good practice and might not be supported in the future

**Comment by hsoft** [comment]
@nicolashainaux would you be interested in maintaining the package? I'd like to get rid of ownership.

**Comment by nicolashainaux** [comment]
Hum, I don't understand its mechanisms very deeply, even if it's not a very long script, I can see it's bound to Sphinx. Not sure to be able to answer to questions or to bring it improvements later.

So I must say it's a temptation to say yes mainly because it would mean I would be able to update the PyPI version. But on another hand, it would be stupid not understanding it deep enough. I am not sure I would be able to resolve issue #4 (improvement), for instance, without a lot of time. Would you stay around as contributor at least?

**Comment by hsoft** [comment]
Sorry @nicolashainaux , I'm really looking into getting rid of this ownership. I don't use it.

**Comment by nicolashainaux** [comment]
Alright then, as you don't use it, and as I use it, it would be better that I take ownership.

**Comment by hsoft** [comment]
What is your pypi username?

**Comment by nicolashainaux** [comment]
Same as here: nicolashainaux

**Comment by hsoft** [comment]
@nicolashainaux a little late (I've been busy, sorry), but it's done.

**Comment by nicolashainaux** [comment]
I just published the version containing the patch on PyPI, so I close this issue and the related ones.
